# Alternative Dockerfile: skips the 'npm run build' part

## Production stage
FROM nginx:stable-alpine

# copy static files from a local folder 'build' to serve
COPY ./build /usr/share/nginx/html

# copy nginx config, apparently this is needed if React Router is being used
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]